apiVersion: v2
name: discourse
description: A community-maintained Helm chart for deploying Discourse.
type: application
version: 0.1.0
appVersion: "3.3.0"
home: https://www.discourse.org/
sources:
  - https://github.com/discourse/discourse
keywords:
  - discourse
  - forum
  - community
maintainers:
  - name: discourse-helm maintainers
