apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
data:
  DISCOURSE_HOSTNAME: {{ .Values.discourse.hostname | quote }}
  DISCOURSE_DEVELOPER_EMAILS: {{ .Values.discourse.developerEmails | quote }}
  DISCOURSE_SMTP_ADDRESS: {{ .Values.discourse.smtp.address | quote }}
  DISCOURSE_SMTP_PORT: {{ .Values.discourse.smtp.port | quote }}
  DISCOURSE_SMTP_AUTHENTICATION: {{ .Values.discourse.smtp.authentication | quote }}
  DISCOURSE_SMTP_ENABLE_START_TLS: {{ .Values.discourse.smtp.enableStartTls | quote }}
  DISCOURSE_DB_HOST: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
  DISCOURSE_DB_PORT: {{ .Values.postgresql.port | quote }}
  DISCOURSE_DB_NAME: {{ .Values.postgresql.database | quote }}
  DISCOURSE_REDIS_HOST: {{ default (printf "%s-redis-master" .Release.Name) .Values.redis.host | quote }}
  DISCOURSE_REDIS_PORT: {{ .Values.redis.port | quote }}
