{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "discourse.fullname" $ }}-{{ .name }}
  labels:
    {{- include "discourse.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name | quote }}
spec:
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: {{ default 3 .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "discourse.serviceAccountName" $ }}
          containers:
            - name: {{ .name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                {{- toYaml .command | nindent 16 }}
              envFrom:
                {{- include "discourse.envFrom" $ | nindent 16 }}
              env:
                {{- include "discourse.secretEnv" $ | nindent 16 }}
{{- end }}
