{{- if .Values.migrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "discourse.fullname" . }}-migrate
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrationJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrationJob.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "discourse.serviceAccountName" . }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.migrationJob.command | nindent 12 }}
          envFrom:
            {{- include "discourse.envFrom" . | nindent 12 }}
          env:
            {{- include "discourse.secretEnv" . | nindent 12 }}
{{- end }}
{{- if .Values.startupJob.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "discourse.fullname" . }}-startup
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: startup
spec:
  backoffLimit: {{ .Values.startupJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.startupJob.ttlSecondsAfterFinished }}
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "discourse.serviceAccountName" . }}
      containers:
        - name: startup
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.startupJob.command | nindent 12 }}
          envFrom:
            {{- include "discourse.envFrom" . | nindent 12 }}
          env:
            {{- include "discourse.secretEnv" . | nindent 12 }}
{{- end }}
