apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCOURSE_DB_USERNAME: {{ .Values.postgresql.username | quote }}
  DISCOURSE_DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  DISCOURSE_SMTP_USER_NAME: {{ .Values.discourse.smtp.username | quote }}
  DISCOURSE_SMTP_PASSWORD: {{ .Values.discourse.smtp.password | quote }}
  DISCOURSE_REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  DISCOURSE_S3_ACCESS_KEY_ID: {{ .Values.discourse.s3.accessKeyId | quote }}
  DISCOURSE_S3_SECRET_ACCESS_KEY: {{ .Values.discourse.s3.secretAccessKey | quote }}
